services:
    postgres:
        image: postgres:16-alpine
        container_name: ecommerce_postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_MULTIPLE_DATABASES: user_db,product_db,cart_db,order_db,payment_db,notification_db
        volumes:
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postrgresql/data
        ports:
            - '5432:5432'
        networks:
            - ecommerce_network
    pgadmin:
        image: dpage/pgadmin4
        container_name: ecommerce_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        networks:
            - ecommerce_network
        depends_on:
            - postgres

networks:
    ecommerce_network:
        driver: bridge

volumes:
    postgres_data:
